- name: Deploy and change application
  hosts: localhost
  tasks:
    - name: Run deploy.yml
      ansible.builtin.shell:
        cmd: ansible-playbook /home/ubuntu/deploy/deploy.yml

    - name: Run change.yml
      ansible.builtin.shell:
        cmd: ansible-playbook /home/ubuntu/deploy/change.yml
      ignore_errors: true

    - name: Run install.yml
      ansible.builtin.shell:
        cmd: ansible-playbook /home/ubuntu/deploy/install.yml
      ignore_errors: true
